# Generated by Django 2.2.10 on 2020-04-30 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KLADRRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('code_kladr', models.CharField(max_length=32, verbose_name='Код КЛАДР')),
                ('post_index', models.CharField(max_length=32, verbose_name='Почтовый индекс')),
                ('code_okato', models.CharField(max_length=32, verbose_name='Код ОКАТО')),
                ('tax_code', models.CharField(max_length=32, verbose_name='Налоговый код')),
                ('region_code', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'регион кладр',
                'verbose_name_plural': 'регионы кладр',
            },
        ),
        migrations.CreateModel(
            name='KLADRDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('code_kladr', models.CharField(max_length=32, verbose_name='Код КЛАДР')),
                ('post_index', models.CharField(max_length=32, verbose_name='Почтовый индекс')),
                ('code_okato', models.CharField(max_length=32, verbose_name='Код ОКАТО')),
                ('tax_code', models.CharField(max_length=32, verbose_name='Налоговый код')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_kladr_rf.KLADRRegion', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'район кладр',
                'verbose_name_plural': 'район кладр',
            },
        ),
        migrations.CreateModel(
            name='KLADRCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('code_kladr', models.CharField(max_length=32, verbose_name='Код КЛАДР')),
                ('post_index', models.CharField(max_length=32, verbose_name='Почтовый индекс')),
                ('code_okato', models.CharField(max_length=32, verbose_name='Код ОКАТО')),
                ('tax_code', models.CharField(max_length=32, verbose_name='Налоговый код')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_kladr_rf.KLADRRegion', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'город кладр',
                'verbose_name_plural': 'город кладр',
            },
        ),
    ]
